name: flutter_youtrust_lt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_to: ^0.3.2
  flutter:
    sdk: flutter
  flutter_deck: ^0.18.0
  flutter_localizations:
    sdk: flutter
  intl: any
  springster: ^0.4.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
